# Generated by Django 3.2.3 on 2022-08-24 17:03

from django.db import migrations, models
import login_details.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(auto_now_add=True)),
                ('login_time', models.TimeField(auto_now_add=True)),
                ('authenticated_user', models.BooleanField(default=False)),
                ('enrollment_number', models.BigIntegerField(blank=True, null=True)),
                ('processed_img', models.ImageField(blank=True, null=True, upload_to=login_details.models.processed_image_path)),
            ],
            options={
                'verbose_name': 'Login Detail',
                'ordering': ['-id'],
            },
        ),
    ]
