# Generated by Django 3.2.3 on 2022-05-09 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login_details.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recognizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(auto_now_add=True)),
                ('login_time', models.TimeField(auto_now_add=True)),
                ('authenticated_user', models.BooleanField(default=False)),
                ('enrollment_number', models.BigIntegerField(blank=True, null=True)),
                ('processed_img', models.ImageField(blank=True, null=True, upload_to=login_details.models.processed_image_path)),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recognizer.lectruemodel')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_details_with_teacher', to='recognizer.teacherprofilemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Detail',
                'ordering': ['-id'],
            },
        ),
    ]
