# Generated by Django 3.2.3 on 2022-08-24 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_details', '0001_initial'),
        ('recognizer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_login_details', to='recognizer.lectruemodel'),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_details_with_teacher', to='recognizer.userprofile'),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attandence', to=settings.AUTH_USER_MODEL),
        ),
    ]
