# Generated by Django 3.2.3 on 2022-05-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_details', '0002_alter_logindetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='bit64_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
