# Generated by Django 3.2.3 on 2022-05-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_details', '0003_logindetails_bit64_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='enrollment_number',
            field=models.BigIntegerField(default=190280111140),
        ),
    ]
