# Generated by Django 3.2.3 on 2022-04-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_details', '0003_alter_logindetails_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='enrollment_number',
            field=models.IntegerField(default=0),
        ),
    ]
