# Generated by Django 3.2.3 on 2022-05-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_details', '0004_alter_logindetails_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='enrollment_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
