# Generated by Django 3.2.3 on 2022-05-04 19:36

from django.db import migrations, models
import login_details.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_details', '0004_logindetails_enrollment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='processed_img',
            field=models.ImageField(blank=True, null=True, upload_to=login_details.models.processed_image_path),
        ),
    ]
