# Generated by Django 3.2.3 on 2022-08-24 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recognizer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
        ('login_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectrueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester')], default='1', max_length=1)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('time_to_expire_session', models.IntegerField(default=5)),
                ('allow_recognize', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=recognizer.models.user_image_path)),
                ('about', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=2)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester')], default='1', max_length=3)),
                ('enrollment_number', models.BigIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_username', models.CharField(blank=True, max_length=100, null=True)),
                ('login_proceed', models.BooleanField(default=False)),
                ('ip_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.collegebranchmodel')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.citycollegemodel')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.collegemodel')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.districtcollege')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionAttendanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=recognizer.models.get_session_name, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('atendees', models.ManyToManyField(blank=True, related_name='sessions', to='login_details.LoginDetails')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_website_objects_lecture', to='recognizer.lectruemodel')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_website_objects', to='recognizer.userprofile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='lectruemodel',
            name='accepted_user',
            field=models.ManyToManyField(blank=True, related_name='accepted_lectures', to='recognizer.UserProfile'),
        ),
        migrations.AddField(
            model_name='lectruemodel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.collegebranchmodel'),
        ),
        migrations.AddField(
            model_name='lectruemodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.citycollegemodel'),
        ),
        migrations.AddField(
            model_name='lectruemodel',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.collegemodel'),
        ),
        migrations.AddField(
            model_name='lectruemodel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.districtcollege'),
        ),
        migrations.AddField(
            model_name='lectruemodel',
            name='requested_user',
            field=models.ManyToManyField(blank=True, related_name='requested_lectures', to='recognizer.UserProfile'),
        ),
        migrations.AddField(
            model_name='lectruemodel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='recognizer.userprofile'),
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ip_address', to='recognizer.userprofile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lectruemodel',
            unique_together={('teacher', 'lecture_name')},
        ),
    ]
