# Generated by Django 3.2.3 on 2022-05-09 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recognizer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=recognizer.models.user_image_path)),
                ('about', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=2)),
                ('college', models.CharField(choices=[('LDCE', 'LALBHAI DALPATBHAI COLLEGE OF ENGINEERING'), ('NIR', 'NIRMA INSTITUTE'), ('VGCE', 'VISHVAKARMA COLLEGE OF ENGINEERING')], max_length=5)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(choices=[('EC', 'ELECTRONICS AND COMMUNICATION'), ('CE', 'COMPUTER ENGINEERING'), ('IT', 'INFORMATION AND TECHNOLOGY')], max_length=3)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester')], default='1', max_length=1)),
                ('enrollment_number', models.BigIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_username', models.CharField(blank=True, max_length=100, null=True)),
                ('login_proceed', models.BooleanField(default=False)),
                ('updated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip1', models.CharField(blank=True, max_length=15, null=True)),
                ('ip2', models.CharField(blank=True, max_length=15, null=True)),
                ('about', models.CharField(blank=True, max_length=30, null=True)),
                ('college', models.CharField(blank=True, choices=[('LDCE', 'LALBHAI DALPATBHAI COLLEGE OF ENGINEERING'), ('NIR', 'NIRMA INSTITUTE'), ('VGCE', 'VISHVAKARMA COLLEGE OF ENGINEERING')], max_length=5, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, choices=[('EC', 'ELECTRONICS AND COMMUNICATION'), ('CE', 'COMPUTER ENGINEERING'), ('IT', 'INFORMATION AND TECHNOLOGY')], max_length=3, null=True)),
                ('login_proceed', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LectrueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(default='', max_length=100)),
                ('semester', models.CharField(default='1', max_length=1, verbose_name=(('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester')))),
                ('branch', models.CharField(blank=True, choices=[('EC', 'ELECTRONICS AND COMMUNICATION'), ('CE', 'COMPUTER ENGINEERING'), ('IT', 'INFORMATION AND TECHNOLOGY')], max_length=5, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='recognizer.teacherprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress1', models.CharField(blank=True, max_length=100, null=True)),
                ('ipAddress2', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognizer.teacherprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeWebsiteCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognize', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_website_objects', to='recognizer.teacherprofilemodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
