# Generated by Django 3.2.3 on 2022-08-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionattendancemodel',
            name='name',
            field=models.CharField(default='Special Lecture', max_length=255),
        ),
    ]
