# Generated by Django 3.2.3 on 2022-05-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0002_auto_20220509_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bit64_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
