# Generated by Django 3.2.15 on 2022-08-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0002_alter_sessionattendancemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester'), ('7', '7th Semester'), ('8', '8th Semester')], default='1', max_length=3),
        ),
    ]
