# Generated by Django 3.2.3 on 2022-05-10 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
        ('recognizer', '0003_userprofile_bit64_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.citycollegemodel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.districtcollege'),
        ),
        migrations.AlterField(
            model_name='teacherprofilemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='enrollment_number',
            field=models.BigIntegerField(default=190280111140),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.BigIntegerField(default=1234567890),
        ),
        migrations.AlterUniqueTogether(
            name='lectruemodel',
            unique_together={('teacher', 'lecture_name')},
        ),
    ]
