# Generated by Django 3.2.15 on 2022-08-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0004_auto_20220829_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattendancemodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
