# Generated by Django 3.2.3 on 2022-05-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0005_alter_teacherprofilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='enrollment_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
