# Generated by Django 3.2.3 on 2022-03-24 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recognizer', '0006_auto_20220321_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=30, null=True)),
                ('college', models.CharField(blank=True, choices=[('LDCE', 'LALBHAI DALPATBHAI COLLEGE OF ENGINEERING'), ('NIR', 'NIRMA INSTITUTE'), ('VGCE', 'VISHVAKARMA COLLEGE OF ENGINEERING')], max_length=5, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, choices=[('EC', 'ELECTRONICS AND COMMUNICATION'), ('CE', 'COMPUTER ENGINEERING'), ('IT', 'INFORMATION AND TECHNOLOGY')], max_length=3, null=True)),
                ('login_proceed', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LectrueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(default='', max_length=100)),
                ('branch', models.CharField(blank=True, choices=[('EC', 'ELECTRONICS AND COMMUNICATION'), ('CE', 'COMPUTER ENGINEERING'), ('IT', 'INFORMATION AND TECHNOLOGY')], max_length=5, null=True)),
                ('associeted_teacher', models.ManyToManyField(blank=True, to='recognizer.TeacherProfileModel')),
            ],
        ),
    ]
