# Generated by Django 4.1.7 on 2023-03-28 16:48

from django.db import migrations, models
import django.db.models.deletion
import recognizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('recognizer', '0006_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='You cant fill this text again so be careful, or you can contact your teacher to change text', null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.collegebranchmodel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='college',
            field=models.ForeignKey(blank=True, help_text='You cant fill this text again so be careful, or you can contact your teacher to change text', null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.collegemodel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], help_text='You cant fill this gender again so be careful, or you can contact your teacher to change gender', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='You cant fill this image again so be careful, or you can contact your teacher to change image', max_length=500, null=True, upload_to=recognizer.models.user_image_path),
        ),
    ]
