# Generated by Django 3.2.3 on 2022-05-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0006_auto_20220511_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('EC', 'ELECTRONICS AND COMMUNICATION'), ('CE', 'COMPUTER ENGINEERING'), ('IT', 'INFORMATION AND TECHNOLOGY')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, choices=[('LDCE', 'LALBHAI DALPATBHAI COLLEGE OF ENGINEERING'), ('NIR', 'NIRMA INSTITUTE'), ('VGCE', 'VISHVAKARMA COLLEGE OF ENGINEERING')], max_length=5, null=True),
        ),
    ]
