# Generated by Django 3.2.3 on 2022-03-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0007_lectruemodel_teacherprofilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeWebsiteCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
