# Generated by Django 4.1.7 on 2023-06-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0007_alter_userprofile_branch_alter_userprofile_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectruemodel',
            name='semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester'), ('7', '7th Semester'), ('8', '8th Semester')], default='1', max_length=1),
        ),
    ]
