# Generated by Django 3.2.3 on 2022-05-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0007_auto_20220511_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectruemodel',
            name='lecture_name',
            field=models.CharField(max_length=100),
        ),
    ]
