# Generated by Django 3.2.3 on 2022-05-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0008_alter_lectruemodel_lecture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='changewebsitecount',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_website_objects_lecture', to='recognizer.lectruemodel'),
        ),
    ]
