# Generated by Django 3.2.3 on 2022-03-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0008_changewebsitecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='changewebsitecount',
            name='recognize',
            field=models.BooleanField(default=True),
        ),
    ]
