# Generated by Django 3.2.3 on 2022-05-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0009_changewebsitecount_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='changewebsitecount',
            name='atendees',
            field=models.ManyToManyField(blank=True, null=True, related_name='sessions', to='recognizer.UserProfile'),
        ),
        migrations.AddField(
            model_name='lectruemodel',
            name='accepted_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='accepted_lectures', to='recognizer.UserProfile'),
        ),
        migrations.AddField(
            model_name='lectruemodel',
            name='requested_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='requested_lectures', to='recognizer.UserProfile'),
        ),
    ]
