# Generated by Django 3.2.3 on 2022-03-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0010_auto_20220324_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeWebsiteCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognize', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
