# Generated by Django 3.2.3 on 2022-05-31 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recognizer', '0011_auto_20220522_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofilemodel',
            name='add_extra_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofilemodel',
            name='time_in_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='teacherprofilemodel',
            name='time_limit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacherprofilemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
