# Generated by Django 3.2.3 on 2022-04-01 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0011_changewebsitecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='changewebsitecount',
            name='associated_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recognizer.teacherprofilemodel'),
        ),
    ]
