# Generated by Django 3.2.3 on 2022-05-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_details', '0005_alter_logindetails_enrollment_number'),
        ('recognizer', '0012_auto_20220531_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changewebsitecount',
            name='atendees',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='login_details.LoginDetails'),
        ),
    ]
