# Generated by Django 3.2.3 on 2022-04-01 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0013_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changewebsitecount',
            name='associated_teacher',
        ),
        migrations.AddField(
            model_name='changewebsitecount',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_website_objects', to='recognizer.teacherprofilemodel'),
        ),
    ]
