# Generated by Django 3.2.3 on 2022-04-01 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0014_auto_20220401_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changewebsitecount',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_website_objects', to='recognizer.teacherprofilemodel'),
        ),
    ]
