# Generated by Django 3.2.3 on 2022-04-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0015_alter_changewebsitecount_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectruemodel',
            name='associeted_teacher',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='recognizer.TeacherProfileModel'),
        ),
    ]
