# Generated by Django 3.2.3 on 2022-04-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0016_alter_lectruemodel_associeted_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectruemodel',
            old_name='associeted_teacher',
            new_name='teacher',
        ),
    ]
