# Generated by Django 3.2.3 on 2022-04-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0017_rename_associeted_teacher_lectruemodel_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectruemodel',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lectruemodel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='recognizer.teacherprofilemodel'),
        ),
    ]
