# Generated by Django 3.2.3 on 2022-05-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0018_auto_20220401_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress1', models.CharField(blank=True, max_length=100, null=True)),
                ('ipAddress2', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognizer.teacherprofilemodel')),
            ],
        ),
    ]
