# Generated by Django 3.2.3 on 2022-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0020_auto_20220508_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofilemodel',
            name='ip1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofilemodel',
            name='ip2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
