# Generated by Django 3.2.3 on 2022-05-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0021_auto_20220508_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectruemodel',
            name='semester',
            field=models.CharField(default='1', max_length=1, verbose_name=(('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester'))),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester')], default='1', max_length=1),
        ),
    ]
